# Generated by Django 4.2.11 on 2024-04-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="last_login",
            field=models.DateTimeField(db_comment="上次登录时间", null=True),
        ),
    ]
