# Generated by Django 4.2.11 on 2024-06-18 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Account", "0002_alter_user_last_login"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="access_system_h",
            field=models.BooleanField(default=False),
        ),
    ]
