# Generated by Django 4.2.16 on 2024-11-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0003_user_access_system_g_user_access_system_h"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="access_system_g",
            field=models.BooleanField(default=False),
        ),
    ]
