# Generated by Django 4.2.16 on 2025-01-03 13:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Account", "0004_user_access_system_g"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="access_system_e",
            new_name="access_system_v",
        ),
        migrations.AddField(
            model_name="user",
            name="access_system_z",
            field=models.BooleanField(default=False),
        ),
    ]
