name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  workflow:
    uses: Intelligent-Curtain-Wall/.workflows/.github/workflows/ci-cd-pipeline.yml@main
    with:
      image-tag: user-authentication
    secrets:
      WORKFLOW_PRIVATE_KEY: ${{ secrets.WORKFLOW_PRIVATE_KEY }}